name: PS2-ELF-Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mips64-linux-gnu

      - name: Compile ELF
        run: |
          mips64-linux-gnu-gcc main.c -o ps2_emulator.elf -nostdlib

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps2-elf-file
          path: ps2_emulator.elf
      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps2-elf-file
          path: ps2_emulator.elf
