name: PS2-ELF-Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PS2DEV Toolchain
        uses: ps2dev/setup-ps2dev@v1
        with:
          with-ports: false

      - name: Compile ELF
        run: |
          ee-gcc main.c -o ps2_emulator.elf -lkernel -ldebug

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps2-elf-file
          path: ps2_emulator.elf
